package rules

import com.sample.DroolsTest.*;
import com.java.*;

rule "Monster picked"
	salience 100
	when
		Fact(name("chosen"), value(true))
	then
		Contact.showMessage("chosen");
		drools.halt();
end

rule "No monster"
	salience -1
	when
	then
		Contact.showMessage("not_chosen");
		drools.halt();
end

rule "Ask about profession"
	salience 90
	when
	then
		Contact.askQuestion("profession");
end

rule "What wand do you want to use?"
	salience 7
	when
		Fact(name("profession"), value("sorc"))
	then
		Contact.askQuestion("wand_type");
end

rule "What rod do you want to use?"
	salience 7
	when
		Fact(name("profession"), value("druid"))
	then
		Contact.askQuestion("rod_type");
end

rule "What level interval do you have?"
	salience 20
	when
		Fact(name("profession"))
	then
		Contact.askQuestion("level");
end

rule "Into what place would you like to go?"
	salience 8
	when
		Fact(name("profession"))
		Fact(name("level"))
	then
		Contact.askQuestion("place");
end

rule "Would you attack an animal?"
	salience 8
	when
		Fact(name("witcher_wannabe"), value(false))
		Fact(name("profession"))
		Fact(name("level"))
	then
		Contact.askQuestion("animal_killer");
end

rule "Would you attack a person?"
	salience 8
	when
		Fact(name("animal_killer"), value(true))
		Fact(name("profession"))
		Fact(name("level"))
	then
		Contact.askQuestion("person_killer");
end

rule "Are you scared of insects?"
	salience 8
	when
		Fact(name("animal_killer"), value(false))
		not Fact(name("rat_fear"))
		Fact(name("profession"))
		Fact(name("level"))
	then
		Contact.askQuestion("insect_killer");
end

rule "Are you scared of rats?"
	salience 8
	when
		Fact(name("animal_killer"), value(false))
		not Fact(name("insect_killer"))
		Fact(name("level"), value("jeden"))
	then
		Contact.askQuestion("rat_fear");
end

rule "Do you like horrors?"
	salience 8
	when
	    Fact(name("witcher_wannabe"), value(true))
	    not Fact(name("monster_killer"))
		Fact(name("profession"))
		Fact(name("level"))
	then
		Contact.askQuestion("horror_like");
end

rule "Do you like monsters?"
	salience 8
	when
	    Fact(name("witcher_wannabe"), value(true))
	    not Fact(name("horror_like"))
		Fact(name("profession"))
		Fact(name("level"))
	then
		Contact.askQuestion("monster_killer");
end

rule "Do you want to be like a Witcher?"
	salience 9
	when
		Fact(name("profession"))
		Fact(name("level"))
	then
		Contact.askQuestion("witcher_wannabe");
end

